### PR TITLE
fixing #1293

### PR DESCRIPTION
**Pull request by sarthakpati**
Fixes issue #1293

## Proposed Changes
  - added a check if the output is defined as a directory or not

### CODE REVIEW

**Comment by sarthakpati** [comment]
Ready for review @ashishsingh18 @AlexanderGetka-cbica

**Review by AlexanderGetka-cbica — APPROVED** [review]

**Review by ashishsingh18 — APPROVED** [review]

**Comment by sarthakpati** [comment]
@AlexanderGetka-cbica : All Windows builds on sbia-pc132 (Phuc's old machine) are failing (I am assuming because of lack of space). Can we either remove this agent from the pool OR get this issue fixed?

**Comment by AlexanderGetka-cbica** [comment]
@sarthakpati I think temporarily disabling it is best -- can you go to 
https://dev.azure.com/CBICA/CaPTk/_settings/agentqueues?queueId=58&view=agents
and disable the SBIA-PC132 agent from there? I don't actually have permissions to do this.

**Comment by sarthakpati** [comment]
> @sarthakpati I think temporarily disabling it is best -- can you go to
> https://dev.azure.com/CBICA/CaPTk/_settings/agentqueues?queueId=58&view=agents
> and disable the SBIA-PC132 agent from there? I don't actually have permissions to do this.

Done.

**Pull request merged**
