### PR TITLE
PSP and EGFRvIII fixes

### PR DESCRIPTION
**Pull request by saimarathore**

### CODE REVIEW

**Comment by sarthakpati** [comment]
The [artefacts](https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1804&view=artifacts&type=publishedArtifacts) for this build are ready. @saimarathore: do you think we can test which issues these changes are fixing?

**Comment by sarthakpati** [comment]
> The [artefacts](https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1804&view=artifacts&type=publishedArtifacts) for this build are ready. @saimarathore: do you think we can test which issues these changes are fixing?

#1078 still present:

```powershell
(base) PS C:\CaPTk_Full\1.8.0.nonRelease.20200705.a0ea38c9\bin> .\PseudoProgressionEstimator.exe -i "C:\PseudoProgressionEstimator" -o "C:\Users\sarth\Downloads\test_psp" -t 1 -m "C:\PseudoProgressionEstimator_Model"
Input directory name:C:\PseudoProgressionEstimator
Output directory name:C:\test_psp
Model directory name:C:\PseudoProgressionEstimator_Model
Module loaded: Pseudoprogression Estimation on Existing Model:
2ABEM
ABFC
Number of subjects with required input: 2
Loading Perfusion Image: 0
Loading Perfusion Image: 1
```

**Comment by saimarathore** [comment]
> > The [artefacts](https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1804&view=artifacts&type=publishedArtifacts) for this build are ready. @saimarathore: do you think we can test which issues these changes are fixing?
> 
> #1078 still present:
> 
> ```powershell
> (base) PS C:\CaPTk_Full\1.8.0.nonRelease.20200705.a0ea38c9\bin> .\PseudoProgressionEstimator.exe \
> -i "C:\PseudoProgressionEstimator" \
> -o "C:\Users\sarth\Downloads\test_psp" \
> -m "C:\PseudoProgressionEstimator_Model" \
> -t 1 
> Input directory name:C:\PseudoProgressionEstimator
> Output directory name:C:\test_psp
> Model directory name:C:\PseudoProgressionEstimator_Model
> Module loaded: Pseudoprogression Estimation on Existing Model:
> 2ABEM
> ABFC
> Number of subjects with required input: 2
> Loading Perfusion Image: 0
> Loading Perfusion Image: 1
> ```

This PR addresses #1078.

**Comment by AlexanderGetka-cbica** [comment]
Does this also address #1162 ?

**Comment by sarthakpati** [comment]
> > > The [artefacts](https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1804&view=artifacts&type=publishedArtifacts) for this build are ready. @saimarathore: do you think we can test which issues these changes are fixing?
> > 
> > 
> > #1078 still present:
> > ```powershell
> > (base) PS C:\CaPTk_Full\1.8.0.nonRelease.20200705.a0ea38c9\bin> .\PseudoProgressionEstimator.exe \
> > -i "C:\PseudoProgressionEstimator" \
> > -o "C:\Users\sarth\Downloads\test_psp" \
> > -m "C:\PseudoProgressionEstimator_Model" \
> > -t 1 
> > Input directory name:C:\PseudoProgressionEstimator
> > Output directory name:C:\test_psp
> > Model directory name:C:\PseudoProgressionEstimator_Model
> > Module loaded: Pseudoprogression Estimation on Existing Model:
> > 2ABEM
> > ABFC
> > Number of subjects with required input: 2
> > Loading Perfusion Image: 0
> > Loading Perfusion Image: 1
> > ```
> 
> This PR addresses #1078.

The output directory was empty when I tried it, as I had seen in the original issue. Does the sample data need to be updated?

**Comment by saimarathore** [comment]
> > > > The [artefacts](https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1804&view=artifacts&type=publishedArtifacts) for this build are ready. @saimarathore: do you think we can test which issues these changes are fixing?
> > > 
> > > 
> > > #1078 still present:
> > > ```powershell
> > > (base) PS C:\CaPTk_Full\1.8.0.nonRelease.20200705.a0ea38c9\bin> .\PseudoProgressionEstimator.exe \
> > > -i "C:\PseudoProgressionEstimator" \
> > > -o "C:\Users\sarth\Downloads\test_psp" \
> > > -m "C:\PseudoProgressionEstimator_Model" \
> > > -t 1 
> > > Input directory name:C:\PseudoProgressionEstimator
> > > Output directory name:C:\test_psp
> > > Model directory name:C:\PseudoProgressionEstimator_Model
> > > Module loaded: Pseudoprogression Estimation on Existing Model:
> > > 2ABEM
> > > ABFC
> > > Number of subjects with required input: 2
> > > Loading Perfusion Image: 0
> > > Loading Perfusion Image: 1
> > > ```
> > 
> > 
> > This PR addresses #1078.
> 
> The output directory was empty when I tried it, as I had seen in the original issue. Does the sample data need to be updated?



model needs to be updated. i have shared the model with @ashishsingh18.

**Comment by saimarathore** [comment]
> Does this also address #1162 ?

There was no change in the code required for #1162. The link of the EGFRvIII SVM model was somehow pointing to older version of the model. @ashishsingh18 will upload the right version of the model.

**Comment by sarthakpati** [comment]
> > > > > The [artefacts](https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1804&view=artifacts&type=publishedArtifacts) for this build are ready. @saimarathore: do you think we can test which issues these changes are fixing?
> > > > 
> > > > 
> > > > #1078 still present:
> > > > ```powershell
> > > > (base) PS C:\CaPTk_Full\1.8.0.nonRelease.20200705.a0ea38c9\bin> .\PseudoProgressionEstimator.exe \
> > > > -i "C:\PseudoProgressionEstimator" \
> > > > -o "C:\Users\sarth\Downloads\test_psp" \
> > > > -m "C:\PseudoProgressionEstimator_Model" \
> > > > -t 1 
> > > > Input directory name:C:\PseudoProgressionEstimator
> > > > Output directory name:C:\test_psp
> > > > Model directory name:C:\PseudoProgressionEstimator_Model
> > > > Module loaded: Pseudoprogression Estimation on Existing Model:
> > > > 2ABEM
> > > > ABFC
> > > > Number of subjects with required input: 2
> > > > Loading Perfusion Image: 0
> > > > Loading Perfusion Image: 1
> > > > ```
> > > 
> > > 
> > > This PR addresses #1078.
> > 
> > 
> > The output directory was empty when I tried it, as I had seen in the original issue. Does the sample data need to be updated?
> 
> model needs to be updated. i have shared the model with @ashishsingh18.

Cool! I hope he updates this soon. Also, did you have a chance to look at the email I sent you about the error I get during training using some of the brain tumor data?

**Comment by sarthakpati** [comment]
> > The output directory was empty when I tried it, as I had seen in the original issue. Does the sample data need to be updated?
> 
> model needs to be updated. i have shared the model with @ashishsingh18.

The testing is now producing results with this PR and the updated model:

```powershell
(base) PS C:\CaPTk_Full\1.8.0.nonRelease.20200707.15826566\bin> .\PseudoProgressionEstimator.exe -m "C:\PseudoProgressionEstimator_PretrainedModel_new\" -i "C:\PseudoProgressionEstimator" -o "C:\test_psp" -t 1
Input directory name:C:\PseudoProgressionEstimator
Output directory name:C:\test_psp
Model directory name:C:\PseudoProgressionEstimator_PretrainedModel_new\
Module loaded: Pseudoprogression Estimation on Existing Model:
2ABEM
ABFC
Number of subjects with required input: 2
Loading Perfusion Image: 0
Loading Perfusion Image: 1
Revising Perfusion Image: 0
Revising Perfusion Image: 1
Loading and processing Feature (testing): 0
Shape and neuro features calculated.
Counter Size (testing): 40
Counter Size (testing): 75
Counter Size (testing): 110
Counter Size (testing): 145
Counter Size (testing): 180
Counter Size (testing): 215
Counter Size (testing): 250
Counter Size (testing): 285
Counter Size (testing): 320
Counter Size (testing): 355
Counter Size (testing): 390
Counter Size (testing): 425
Counter Size (testing): 460
Counter Size (testing): 495
Counter Size (testing): 530
Counter Size (testing): 565
Counter Size (testing): 600
Counter Size (testing): 635
Counter Size (testing): 670
Counter Size (testing): 705
Counter Size (testing): 740
Counter Size (testing): 775
Counter Size (testing): 810
Basic features copied in the OtherFeatures map.
Loading and processing Feature (testing): 1
Shape and neuro features calculated.
Counter Size (testing): 40
Counter Size (testing): 75
Counter Size (testing): 110
Counter Size (testing): 145
Counter Size (testing): 180
Counter Size (testing): 215
Counter Size (testing): 250
Counter Size (testing): 285
Counter Size (testing): 320
Counter Size (testing): 355
Counter Size (testing): 390
Counter Size (testing): 425
Counter Size (testing): 460
Counter Size (testing): 495
Counter Size (testing): 530
Counter Size (testing): 565
Counter Size (testing): 600
Counter Size (testing): 635
Counter Size (testing): 670
Counter Size (testing): 705
Counter Size (testing): 740
Counter Size (testing): 775
Counter Size (testing): 810
Basic features copied in the OtherFeatures map.
PCA features of all the modalities copied in the OtherFeatures map.
patient number0
patient number1
FeaturesOfAllSubjects populated.
Feature writing started:
parameters read.
Finished successfully
(base) PS C:\CaPTk_Full\1.8.0.nonRelease.20200707.15826566\bin> ls C:\test_psp


    Directory: C:\test_psp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           07-Jul-20    16:51           1599 PSU_ScaledSelectedFeatures.csv
-a---           07-Jul-20    16:51          40732 RawFeatures.csv
-a---           07-Jul-20    16:51           1062 REC_ScaledSelectedFeatures.csv
-a---           07-Jul-20    16:51             98 results.csv
-a---           07-Jul-20    16:51          39756 ScaledFeatures.csv
```

Confirming that #1078 is fixed with this PR!

**Pull request merged**
