### PR TITLE
1264

### PR DESCRIPTION
**Pull request by sarthakpati**
Fixes issue #1264

## Proposed Changes
  - added rounding of output for mask resampling

### CODE REVIEW

**Comment by sarthakpati** [comment]
@AlexanderGetka-cbica Windows agent seems to be off...

**Comment by AlexanderGetka-cbica** [comment]
Mark was trying to install the agent as a service on SBIA-PC132 and for some reason he can't run the configurator. Some kind of DotNet error that Phuc and I haven't seen before. We're trying to figure this out.

**Comment by sarthakpati** [comment]
> Mark was trying to install the agent as a service on SBIA-PC132 and for some reason he can't run the configurator. Some kind of DotNet error that Phuc and I haven't seen before. We're trying to figure this out.

Oh okay. Do you want me to set this up on my desktop, as well?

**Comment by sarthakpati** [comment]
> > Mark was trying to install the agent as a service on SBIA-PC132 and for some reason he can't run the configurator. Some kind of DotNet error that Phuc and I haven't seen before. We're trying to figure this out.
> 
> Oh okay. Do you want me to set this up on my desktop, as well?

Okay, so I started an agent on my desktop as a service without a hitch. No idea what issue you guys are seeing with sbia-pc132. Have you ensured everything is up to date?

**Comment by AlexanderGetka-cbica** [comment]
The issue is at first glance some sort of missing DotNet DLL. But Mark already tried updating that to fix it. The agent was working earlier on the same machine, in the same directory path, just on a different drive. No idea why it isn't working for Mark, if this is machine specific or what. Anyway, thanks for setting it up on your machine. Gives us a buffer while we figure this out.

**Comment by sarthakpati** [comment]
A weird error is happening; could you please take a look: https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=2198&view=logs&j=1c0c49ae-3689-5695-dc89-172576f8f795&t=38130e40-62cf-547e-0f15-7d2d68fea114

**Comment by AlexanderGetka-cbica** [comment]
From what I can see online, this is some stupidity involving git outputting regular information to stderr and powershell / azure picking it up as a failure. Giving this one more try to see if it's persistent. If it is I'll need to mess with azure-pipelines.yml so it doesn't pick that up. No idea why the git guys thought that was a good idea...

**Comment by sarthakpati** [comment]
> From what I can see online, this is some stupidity involving git outputting regular information to stderr and powershell / azure picking it up as a failure. Giving this one more try to see if it's persistent. If it is I'll need to mess with azure-pipelines.yml so it doesn't pick that up. No idea why the git guys thought that was a good idea...

Sigh, guess this still happening.

**Comment by AlexanderGetka-cbica** [comment]
I pushed another change to #1266, feel free to cancel again if the windows build fails.

**Comment by sarthakpati** [comment]
Okay, since it seemed to be working, I have pulled in your fix here to test.

**Comment by sarthakpati** [comment]
> I pushed another change to #1266, feel free to cancel again if the windows build fails.

Your change has fixed the build! Thanks.

**Pull request merged**
