### PR TITLE
Critical: Fix CWL generation bug

### PR DESCRIPTION
**Pull request by surrsurus**
- Fix CWL generation bug on windows
- Make CMDparser far more strict about the exe_names

### CODE REVIEW

**Comment by surrsurus** [comment]
Okay, added sarthak's latest changes to the PR. Building on linux gets a lot of cmake errors, and I'll be resolving them in the next few commits. Error log:

```
CMake Error at src/applications/FeatureExtraction/CMakeLists.txt:22 (INCLUDE):
  INCLUDE could not find load file:

    /home/gray/CBICA/git/CaPTk/src/applications/FeatureExtraction/../../../cmake_modules/CaPTk_Macros.cmake


-- Found OpenMP: -fopenmp
CMake Error at src/applications/Preprocessing/CMakeLists.txt:22 (INCLUDE):
  INCLUDE could not find load file:

    /home/gray/CBICA/git/CaPTk/src/applications/Preprocessing/../../../cmake_modules/CaPTk_Macros.cmake


CMake Error at CMakeLists.txt:532 (CAPTK_ADD_EXECUTABLE):
  CAPTK_ADD_EXECUTABLE Macro invoked with incorrect arguments for macro
  named: CAPTK_ADD_EXECUTABLE


CMake Error at CMakeLists.txt:536 (SET_TARGET_PROPERTIES):
  SET_TARGET_PROPERTIES Can not find target to add properties to: Confetti


CMake Error at CMakeLists.txt:574 (INSTALL):
  INSTALL TARGETS given target "Confetti" which does not exist in this
  directory.

```

**Comment by surrsurus** [comment]
Ok so the first two errors are because the relative path (../../../) needs an extra ../ since I'm building in `./bin`. Will adding that break the windows build @sarthakpati ?

**Comment by surrsurus** [comment]
Next error is because the macro is defined as `MACRO( CAPTK_ADD_EXECUTABLE APPLICATION SOURCESFILES DEPENDENT_LIBS )` however the root cmake lists tries to invoke `CAPTK_ADD_EXECUTABLE(${STANDALONE_APP_NAME} "${ConfettiSrcs} ${ConfettiHeaders}" "${OpenCV_LIBS} ${ITK_LIBRARIES}")`

**Comment by surrsurus** [comment]
And I'm going to assume that the remaining errors are cascading as a result of Confetti not being able to be built.

**Comment by surrsurus** [comment]
Ok so I think what I'm going to do is revert the changes, merge my version that's working then let Sarthak create a separate pull request once the linux issues are resolved on that branch, since Ashish needs to leave soon and Phuc needs the fix.

**Comment by sarthakpati** [comment]
hey @surrsurus, the relative path `${PROJECT_SOURCE_DIR}/../../../cmake_modules/CaPTk_Macros.cmake` (inside `src/applications/FeatureExtraction` and `src/applications/Preprocessing`) always point within the CaPTk source folder and has nothing to do with where the binary folder is present.

**Comment by surrsurus** [comment]
@sarthakpati just realized it's a path case-sensitivity issue. Macros should be macros.

**Comment by sarthakpati** [comment]
Ah okay. Then this should work now, eh?

**Comment by surrsurus** [comment]
Still have the issue with Confetti on your branch. However I think that's the only remaining issue. I'll merge your changes into this PR if we can get it working after that.

**Comment by sarthakpati** [comment]
I have turned off Confetti compiles. Check now?

**Comment by surrsurus** [comment]
Yep cmake isn't having any issues. I'll build the project on linux, and if that goes well I'll merge your fork with the linux fixes into this PR and merge it into the master.

**Comment by sarthakpati** [comment]
Done. I am testing what is going on with Confetti to make it weird on Linux and make a separate PR related to it.

**Comment by surrsurus** [comment]
Alright I've verified that the changes @sarthakpati made compile on linux, merged them into this PR, and once @PhucNgo1711 builds it, it will be merged in.

**Comment by surrsurus** [comment]
Ok everything is working properly, Phuc just needed to add a special include for OSX in the command parser.

**Pull request merged**
