### PR TITLE
perfusion PCA code clean up and error checks in perfusion derivatives

### PR DESCRIPTION
**Pull request by saimarathore**
perfusion PCA code clean up and error checks in perfusion derivatives

### CODE REVIEW

**Comment by PhucNgo1711** [comment]
@sarthakpati The required checks look good

**Comment by PhucNgo1711** [comment]
@sarthakpati The self-hosted builds are queued because they have to wait for the agents to be done with this first https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1451&view=results

**Comment by sarthakpati** [comment]
@saimarathore @ashishsingh18 is this ready for review?

**Comment by ashishsingh18** [comment]
> 
> 
> @saimarathore @ashishsingh18 is this ready for review?

yes

**Pull request merged**
