### PR TITLE
Fixes related to CBICATk, Feature Extraction, and a few GUI updates

### PR DESCRIPTION
**Pull request by sarthakpati**

### CODE REVIEW

**Comment by sarthakpati** [comment]
Failing because of time-out.

**Comment by surrsurus** [comment]
Noticing that this is only hitting the 50 minute mark and stopping, shouldn't this repo also have 120 minutes?

**Comment by surrsurus** [comment]
Looks like both the master branch and all PR's are limited to 50 minutes too, so it's not an issue purely with this PR.

**Comment by surrsurus** [comment]
Looks like both the master branch and all PR's are limited to 50 minutes too, so it's not an issue purely with this PR.

**Comment by surrsurus** [comment]
Looks like both the master branch and all PR's are limited to 50 minutes too, so it's not an issue purely with this PR.

**Pull request merged**
