### PR TITLE
Fix libomp on mac, fix mac GUI crash

### PR DESCRIPTION
**Pull request by AlexanderGetka-cbica**
This PR addresses #1215 

- Added a cmake directive forcing the configuration to pick up our extracted Qt on Azure. Previously, it was apparently picking up the PyQt libs under anaconda3 and bundling these into the AppImage. This caused the GUI to consistently crash on Mac.
- Added a step to the Azure pipeline that force-patches the Utilities executable to use the bundled OpenMP library. Previously it was always looking for a system installation and this was unresponsive to changes in CMake, even though the other applications responded. This added step prevents the Utilities crash.
- Created a BraTSPipeline cwl file. This allowed BraTSPipeline to be picked up by our automated OpenMP dylib patch during build, preventing the crash Chiharu was seeing.

### CODE REVIEW

**Comment by AlexanderGetka-cbica** [comment]
After spending a very long time in a futile struggle to get Cmake to handle the libomp path, I instead settled for patching the executable in the finished package as part of the Azure pipeline. Something during the "make package" step itself is overriding any other setting for linking against libomp. Anyway, the next artifact this produces is the cleaned-up version of the previous commits. Just needs testing on a Mac machine that doesn't have OpenMP installed. Was hoping to use VNC for this earlier, but i see cbica-osx2 still has OpenMP.

**Comment by AlexanderGetka-cbica** [comment]
@CBICA/devteam This is ready for review (builds from merging master in are pending).

**Comment by AlexanderGetka-cbica** [comment]
I sent it to him and he said he'll try it. I'll update with any news.

**Comment by PhucNgo1711** [comment]
The GUI is fixed

**Comment by sarthakpati** [comment]
> The GUI is fixed

Many thanks, @PhucNgo1711!

**Pull request merged**
