### PR TITLE
Minor fixes 

### PR DESCRIPTION
**Pull request by sarthakpati**
Fixes issue #1148, #1065

## Proposed Changes
  - BraTS similarity measures "improved"
  - rigid registration fix
  - documentation updates

### CODE REVIEW

**Comment by sarthakpati** [comment]
Hey @PhucNgo1711, do you know why this is showing as failed when it has actually passed?

image

**Comment by PhucNgo1711** [comment]
> Hey @PhucNgo1711, do you know why this is showing as failed when it has actually passed?
> 
> image

Hmm looks like Github didn't pick up the rerun attempt. I hate to say this but you might need to do a `Run New` for this.

**Comment by AlexanderGetka-cbica** [comment]
I reran this when it failed last time since it appeared to be a spurious error related to the agent, not to anything on our end. But I did it through Azure rather than hitting the re-run button on GitHub... Maybe there have been changes to how the runs are reflected.

**Comment by PhucNgo1711** [comment]
> I reran this when it failed last time since it appeared to be a spurious error related to the agent, not to anything on our end. But I did it through Azure rather than hitting the re-run button on GitHub... Maybe there have been changes to how the runs are reflected.

This is interesting because I've done the `Rerun failed jobs` a few times and Github was able to properly pick up the 2nd attempt. Not sure why it didn't this time.

**Comment by AlexanderGetka-cbica** [comment]
Let me try rerunning that job from GitHub directly one more time, just in case that forces it to be picked up. Then if not, we can do a full rerun.

**Comment by AlexanderGetka-cbica** [comment]
Yeah, that didn't even actually work. @sarthakpati Might need to push a dummy change for this.

**Comment by PhucNgo1711** [comment]
> Yeah, that didn't even actually work. @sarthakpati Might need to push a dummy change for this.

`Run New` didn't work?

**Comment by AlexanderGetka-cbica** [comment]
I just meant that hitting the Re-run button on _GitHub's_ UI didn't do anything.
Let me try Run New.

**Comment by AlexanderGetka-cbica** [comment]
Okay, looks like it's been picked up now... I'll check back later and see if there's any more weirdness.

**Comment by sarthakpati** [comment]
I pushed some HTML changes here. Let's see if this helps.

**Comment by AlexanderGetka-cbica** [comment]
the earlier manual run I did was stuck running for a very long time and _appeared_ to be stuck on compiling CaPTk... but if you looked at the published artifacts, there actually was an Ubuntu16.04 build artifact available. I've cancelled that run so the agent should be freed up to run on your latest pushed change... but after a few minutes it seems like it still hasn't moved up the queue.

Really thinking this is something wrong with the azure backend. Something is not coordinating/picking up completion correctly... This isn't just our agent. A similar thing happened to the (non-required) end-to-end macOS build

**Comment by sarthakpati** [comment]
Maybe the machine itself is off?

**Comment by AlexanderGetka-cbica** [comment]
Let me try to login to the VM.

**Comment by AlexanderGetka-cbica** [comment]
Can't seem to stop the agent. I guess it's trying to finish processing something first so it won't exit and I can't find a --force parameter or something equivalent.

I ran the diagnostics for the agent. DNS testing succeeded but actually pinging www.bing.com times out. Everything else in the diagnostic seems fine.

**Comment by sarthakpati** [comment]
I have no idea what could cause something like that. Perhaps you should open an RT ticket for Mark to take a look?

**Comment by AlexanderGetka-cbica** [comment]
Yeah, on it. Think it might be related to the network since I can ping my work machine but nothing outside the network.

**Comment by AlexanderGetka-cbica** [comment]
This is running (for real) now. Maybe it was just an outage. Either way, the pipeline is working again.

**Comment by AlexanderGetka-cbica** [comment]
Checks have passed. Approved.

**Comment by sarthakpati** [comment]
> This is running (for real) now. Maybe it was just an outage. Either way, the pipeline is working again.

Welp, wonder what was wrong. Even the [status](https://status.dev.azure.com/) appeared all good. Anyway, this is good to be reviewed, @PhucNgo1711 @ashishsingh18

**Pull request merged**
