### PR TITLE
Fix #804: Debug in linux. Also general fixes to CMAKE_BUILD_TYPE hand…

### LINKED ISSUE #804: [LINUX] CAPTK_BUILD_OPTION builds "Release" regardless of selection (in build, not superbuild)
**Describe the bug**
_title_
Probably related to issue #775 (were the fixes for this ever upstreamed?). Regardless, #775 was for the superbuild, this is for the build.

**To Reproduce**
1. Do "Debug" superbuild. There is no CAPTK_BUILD_OPTION, just set CMAKE_BUILD_TYPE to "Debug" manually.
2. Open cmake in build configure+generate etc
3. Set CMAKE_BUILD_TYPE to "Debug" manually to see it change (this is not needed, but it will make the problem more clear)
4. Set CAPTK_BUILD_OPTION to "DEVELOPER_MODE". 
5. Configure+generate. CMAKE_BUILD_TYPE becomes "Release", instead of remaining Debug.

**CaPTk Version**
1.7.5

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3

### PR DESCRIPTION
**Pull request by dboun**
Fixes issue #804

## Proposed Changes
  - CMAKE_BUILD_TYPE is propagated to the superbuild libraries
  - CMAKE_BUILD_TYPE is a combo box under linux, containing only the Debug and Release option **with Release being the default**
  - CMAKE_BUILD_TYPE is handled in the top-level CMakeLists and not at Superbuild.cmake
  - CAPTK_BUILD_OPTION is removed as it wasn't really contributing anything anymore. These changes continue not allowing users to build debug packages

## Testing
   - Needs testing on Windows, but I think it will work. Someone should also test if the "PACKAGE" project would show up in VS in Debug.

## Discussion
   - Nothing was blocking anyone before or after this PR from building Release "build" and connecting it with a Debug "superbuild". This is outside of the scope of this PR. I don't think it's important to take care of it internally, but if you do open another issue.

### CODE REVIEW

**Comment by dboun** [comment]
> Failing on Windows. Not approved.

Is it because of  ```##[error]Artifact CBICA.CaPTk_installer_Windows not found for build 1104. Please ensure you have published artifacts in any previous phases of the current build.``` ? I don't see anything else failing in azure.

Although in "build & package captk", while it succeeds it says 
```
MSBUILD : error MSB1009: Project file does not exist.
Switch: PACKAGE.vcxproj
ls: cannot access '*_Installer.*': No such file or directory
mv: cannot stat '*_Installer.*': No such file or directory
Finishing: Build & Package CaPTk
```

Please help me understand the issue.

**Comment by dboun** [comment]
Also, "Configure and compile Superbuild" and "Configure and compile CaPTk" run for 2h and 30m respectively and don't show any errors (I think).

**Comment by dboun** [comment]
(after checking the azure output/yml it's clear it doesn't try to build both. But I think it generates both on Windows, which is why it might have taken a bit longer and failed. Hopefully my new commits would resolve this)

**Comment by dboun** [comment]
Windows and linux failed because they run out of space..

**Comment by ashishsingh18** [comment]
@dboun @PhucNgo1711 Windows build is still failing

**Comment by dboun** [comment]
@ashishsingh18 It hasn't rebuilt since we talked about it. I will refresh it when the azure issue gets fixed

**Pull request closed without merging**
