### PR TITLE
added perfusion alignment data #1278

### PR DESCRIPTION
**Pull request by sarthakpati**
Fixes issue #1278

## Proposed Changes
  - added perfusion alignment data for download

### CODE REVIEW

**Comment by AlexanderGetka-cbica** [comment]
@ashishsingh18 Can we merge this in and into your PR branch?

**Comment by ashishsingh18** [comment]
> 
> 
> @ashishsingh18 Can we merge this in and into your PR branch?



> 
> 
> @ashishsingh18 Can we merge this in and into your PR branch?

We should merge this into master, not my PR branch yet. I really want to get my PR artifact tested on Fedora and every merge triggers a re-build which takes another hour.

**Comment by ashishsingh18** [comment]
Isn't there a way to control the Azure builds? For example, in this case, since there is no code change, there is no need for Azure builds.

**Comment by ashishsingh18** [comment]
@CBICA/devteam Builds failing.

**Comment by AlexanderGetka-cbica** [comment]
I'm not aware of any way to control specifically when these builds are needed for a PR to merge. Maybe a sort of file-inclusion filter could be set up (only changes to actual source files cause these builds), but I guess this would need to be done by @sarthakpati or @MarkBergman-cbica .

Regarding builds failing:

> Failed to download Precompiled hausdorff.  Status=67;"Login denied

This is probably a NITRC service outage causing this.

**Pull request merged**
