### PR TITLE
Fix #753 - Loading large files

### LINKED ISSUE #753: Opening very large file wedges machine
Dragged `http://www.dclunie.com/pixelmedimagearchive/upmcdigitalmammotomocollection/index.html
` 

`. . . \MammoTomoUPMC_Case2\Case2 [Case2]\20071120 080520 [ - MAMMOGRAM DIGITAL SCR BILAT]\Series 73200000 [MG - R MLO Breast Tomosynthesis Image]\1.3.6.1.4.1.5962.99.1.2280943358.716200484.1363785608958.406.0.dcm` 

919,574 KB

into Captk window.

Machine became unresponsive, even to ctrl-alt-del, needed hard power cycle.

EDIT: Dragged 159,000KB Nifti that resulted from converting that Dicom to Nifti (converted by Captk) and same crash resulted.

## Expected Behavior

Doesn't do that.

## Desired Behavior

It's okay if I can't do that, it would be better if it failed more gracefully,

## Specifications
 
  - CaPTk v.1.7.3
  - Windows 7 Enterprise
  - SP 1
  - 64-bit
  - Intel Core 15-4570
  - 20GB RAM

### PR DESCRIPTION
**Pull request by dboun**
Fixes issue #753 

## Proposed Changes
  - When files are loaded their total size is calculated
  - Then it is compared with the installed RAM
  - If the combination of files is > than 0.05 of the RAM size a message is shown saying that the images are too big.

(For reference, 0.05 * 8GB = 400MB, 0.05 * 32GB = 1.6GB)

This was tested on Windows + Linux. Needs testing for Mac (@PhucNgo1711 Can you try it?)

### CODE REVIEW

**Comment by sarthakpati** [comment]
Could you update the version ID for this for an independent build [[ref](https://github.com/CBICA/CaPTk/blob/master/CMakeLists.txt#L16)]? Thanks.

**Comment by dboun** [comment]
@sarthakpati I did. The patch value is conflicting with the master branch, not sure if I should accept mine or the repo's.

**Comment by sarthakpati** [comment]
Done.

**Comment by dboun** [comment]
Additional changes that are needed:
- "Proceed anyway?" OK|CANCEL buttons (https://doc.qt.io/qt-5/qmessagebox.html#details)
- Change check from using installed ram to using cbica's available ram functions.
- Log available ram and files size

**Comment by dboun** [comment]
So now this works as before (tested the azure binaries on linux), but it also has:
- Moved the check code to a separate function
- Has "proceed anyway" functionality
- Logs the ram / filesizes.

It could be merged at this state.

It is missing only: Changing the check to use "available ram" instead of "installed ram". @sarthakpati can you point me to the cbica function that returns available ram? I was not able to find it

**Pull request merged**
