### PR TITLE
Documentation Updates

### PR DESCRIPTION
**Pull request by sarthakpati**
Added documentation related to Mark's comment [here](https://github.com/CBICA/CaPTk/issues/506#issuecomment-501365145) and further details for CaPTk's CLI usage.

### CODE REVIEW

**Comment by MarkBergman-cbica** [comment]
The table in the FAQ is a very good start. I'd make it more comprehensive (all applications) and more functionally oriented. If a FAQ is for Frequently Asked Questions, then the 'answers' should be structured from the point of view of the user's questions.

For example, the question might be "How do I run a CaPTk program from the command line" or "What are the names and functions of the command-line programs?" or "What program do I use for a particular task?"

Minor fixes:

The statement about resolution should not be in the "Disclaimer" section.
> This will nee to be present in the user's ~/.bashrc file 

Should be something like

> This will need to be present in the user's shell start up file (.bashrc, .cshrc, .profile, .kshrc, etc) for the settings to be persistent across login sessions.

In **Compatability** -- indicate that support is for 64 bit. Why isn't "CentOS7" in "Tested"?

**Comment by sarthakpati** [comment]
> I'd make it more comprehensive (all applications) and more functionally oriented. 

Would putting such an exhaustive list work the other way for us? Primarily since we are already giving examples for the CLI of each application in the [How To section](https://cbica.github.io/CaPTk/How_To_Guides.html), which I have added as a link in that FAQ section. This also ensures we don't have to maintain the same information in multiple places, potentially subverting an issue where one section gets updated and another doesn't.

**Comment by sarthakpati** [comment]
> For running CaPTk from command line, specifically for Linux, should there be a path to the .cwl file? or is it supposed to just be ${ApplicationName}.cwl ?

Good catch! It should be full path.

**Comment by sarthakpati** [comment]
> 1. FAQs could be a separate page where we list all FAQs similar to (https://vtk.org/Wiki/VTK/FAQ). Our home page could just link to that FAQ page. Otherwise as the FAQ list grows the home page will grow.
> 2. CLI running examples table should separate the generic and specific examples( either highlight or separate table, etc.) It has too much information and can be difficult to follow.
> 3. Compatibility section should be renamed to "Supported Platforms"
> 4. Compatibility table is very confusing. For example: it is very difficult to understand what the "build" column is. The table should be crisp clear. A user should quickly be able to understand what platforms are supported. We may not need unsupported column and untested columns. As example please see: https://doc.qt.io/qt-5/supported-platforms.html
>    http://docs.mitk.org/2016.11/SupportedPlatformsPage.html

1, 3 & 4 are excellent suggestions and I was already in the process of implementing them. The latest push adds these to the review items. However, I feel that 2 will add clutter to the documentation (I have added a CLI section in the getting started page - this way it is always part of the documentation shipped with CaPTk).

**Comment by sarthakpati** [comment]
FYI, the builds are failing currently because NITRC FTP site is down.

**Comment by ashishsingh18** [comment]
This is already looking great with a separate FAQ page and only minimal information on home page. I was looking at creating a separate FAQ page myself after Mark's email. Thanks that you created it. The 2nd item is fine since the information is already available elsewhere. 

I also agree that we shouldn't be basing our documentation on other libraries, but we should understand and follow the best parts from other projects so as to make our docs clearer.

**Comment by ashishsingh18** [comment]
Btw, the builds are still failing perhaps due to NITRC issue.

**Pull request merged**
