### PR TITLE
CI improvments, collaboration improvements, symlink generation

### PR DESCRIPTION
**Pull request by surrsurus**
This PR adds several new things to CaPTk.

  1. Travis CI is now no longer on allowed failure modes as Linux builds are now fully working from end to end. OSX is on the way. Note that there may be a need for cache bootstrapping which may cause this PR to fail the new travis tests. If so, the necessary bootstrapping will be committed to this PR.
  2. Added Pull request and Issue templates. This should help the PRs, and Issues be more uniform and demonstrate/remind collaborators what exactly we want to see in a PR/Issue.
  3. A `captk` symlink is generated as a part of the `make install` step, and a `PostInstall.cmake` file has been added alongside this functionality to make further post install operations have a defined place.
  4. Travis CI scripts have been moved to a .travis folder to keep them out of the way of the general `scripts` directory, as it could potentially be confusing for collaborators to stumble across them and not understand their purpose.
  5. Minor bugfix regarding `cbicaITKUtilities` that prevents builds on gcc.

### CODE REVIEW

**Comment by surrsurus** [comment]
Will be monitoring travis, if it does fail I'll work on it right away, but it will only be a matter of bootstrapping it properly.

**Comment by surrsurus** [comment]
Just checked travis, looks like the cache isn't being picked up. Will begin bootstrapping the cache.

**Comment by surrsurus** [comment]
Alright, after this check the cache will be successfully bootstrapped. In addition, CWL reading improvements have been added as of the latest commit. Will approve merge and begin bootstrapping process once Phuc gets his caching to work.

**Comment by sarthakpati** [comment]
hey @surrsurus, is this good to be approved and merged?

**Comment by surrsurus** [comment]
Added bugfixes related to feature extraction installation, missing typename declarations, and missing namespace identifiers before `isnan`

**Pull request merged**
