### PR TITLE
training module fixes

### PR DESCRIPTION
**Pull request by saimarathore**
training module options fixed from GUI and CLI

### CODE REVIEW

**Review by AlexanderGetka-cbica — APPROVED** [review]
Approving pending builds so that this can be tested ASAP. @saimarathore , can you send me the MATLAB script you mentioned to test the training module commands? I will use them to add commands to test suite.

**Comment by sarthakpati** [comment]
@AlexanderGetka-cbica could you please ensure that this is tested before we merge?

**Comment by AlexanderGetka-cbica** [comment]
Alright, I will ping the dev team once the artifacts have been tested.

**Comment by sarthakpati** [comment]
@AlexanderGetka-cbica: no idea if you have come across this yet, but one mechanism you could possibly use to write the range-based unit test for training module is via CMake itself [[ref](https://cmake.org/cmake/help/latest/command/foreach.html)]:
```cmake
foreach(<loop_var> RANGE <start> <stop> [<step>])
```

**Review by sarthakpati — APPROVED** [review]

**Comment by sarthakpati** [comment]
> @AlexanderGetka-cbica: no idea if you have come across this yet, but one mechanism you could possibly use to write the range-based unit test for training module is via CMake itself [[ref](https://cmake.org/cmake/help/latest/command/foreach.html)]:
> 
> ```cmake
> foreach(<loop_var> RANGE <start> <stop> [<step>])
> ```

Testing is complete and this is good to merge. Unit testing will be part of a separate PR.

**Pull request merged**
