### PR TITLE
headers added in feature files in EGFR

### PR DESCRIPTION
**Pull request by saimarathore**
headers added in feature files in EGFR

### CODE REVIEW

**Comment by ashishsingh18** [comment]
@CBICA/devteam This PR is ready for review.

**Comment by sarthakpati** [comment]
Cannot merge as this PR needs to be re-initialized.

**Comment by ashishsingh18** [comment]
Tagging @saimarathore

**Comment by ashishsingh18** [comment]
@PhucNgo1711 The Windows build seems stuck again. Although if we look at the details, the windows build has succeeded. Any idea why this keeps happening? Also, I don't see the self-hosted ones here. Screenshot below.

image

**Comment by ashishsingh18** [comment]
@saimarathore This needs to be re-triggered. 
@PhucNgo1711 Any insights on why this is happening repeatedly?

**Comment by ashishsingh18** [comment]
@CBICA/devteam Please review this.

**Pull request merged**
