### PR TITLE
PerfusionDerivatives bug fixes and code improvement

### PR DESCRIPTION
**Pull request by saimarathore**
PerfusionDerivative bug fixes and code improvement

### CODE REVIEW

**Comment by ashishsingh18** [comment]
@PhucNgo1711 Mac build seems to have been stuck. The message I see is "stopped hearing from agent..." Screenshot below.
image
Any idea what is going on?

**Comment by AlexanderGetka-cbica** [comment]
Hey all. I ran a manual build of this, and this PR _does_ successfully build on my Ubuntu 18.04 machine.
This automated build seems to be failing at least in part because a directory pkg already exists -- maybe a previous failed build didn't properly clean up?

**Comment by ashishsingh18** [comment]
Merging this

**Comment by ashishsingh18** [comment]
> 
> 
> Hey all. I ran a manual build of this, and this PR _does_ successfully build on my Ubuntu 18.04 machine.
> This automated build seems to be failing at least in part because a directory pkg already exists -- maybe a previous failed build didn't properly clean up?

Thanks @AlexanderGetka-cbica

**Pull request merged**
