### PR TITLE
perfusion alignment code clean-up and testing

### PR DESCRIPTION
**Pull request by saimarathore**
perfusion alignment code clean-up
removed dicom tags
removed extra functions

### CODE REVIEW

**Comment by ashishsingh18** [comment]
@PhucNgo1711 Can you please why this PR failed on Mac OS?

**Comment by ashishsingh18** [comment]
@PhucNgo1711 Any idea about macOS failure?

**Comment by PhucNgo1711** [comment]
> @PhucNgo1711 Any idea about macOS failure?

It's a `make -j2` issue on mac. Sometimes it executes the POST_BUILD commands before the build is done. Rerunning the job would fix it. To save time, don't rerun the whole PR, just click `Rerun failed jobs` on Azure. @AlexanderGetka-cbica

**Comment by ashishsingh18** [comment]
@CBICA/devteam this is ready for review.

**Pull request merged**
